[build]
  # Publish directory
  publish = "turkish-version"
  
  # Build command (not needed for static site)
  command = ""

[build.environment]
  # Node.js version (if needed)
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/"
  to = "/index_full.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/wp-content/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SEO headers
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"